### ISSUE TITLE
Make toggle comment work (ctrl-/)

### ISSUE THREAD

**Issue by Un1Gfn** [colinkiama/sublime-meson#23]
[howto](https://stackoverflow.com/a/27731858/)

[example2](https://github.com/sublimehq/Packages/blob/master/JSON/Comments.tmPreferences)

[example3](https://github.com/sublimehq/Packages/blob/master/Makefile/Comments.tmPreferences)

[comments](https://mesonbuild.com/Syntax.html#comments)

**Comment by colinkiama** [comment]
Thanks for the links! I really appreciate that you created this issue.

I’ll try to start working on this as soon as I can (Which is around 1-2 months).

Everybody is welcome to create a pull request that closes though. I’d be able to merge your changes in pretty quickly.
